[env]
ESP_LOG = "trace"

[target.xtensa-esp32-none-elf]
rustflags = [
    "-C",
    "link-arg=-nostartfiles",
]
runner = "espflash flash --monitor --ignore-app-descriptor"

[build]
target-dir = "./target"
target = ["xtensa-esp32-none-elf", "x86_64-unknown-linux-gnu"]

[alias]
xtask = "run --target x86_64-unknown-linux-gnu --package xtask --"
