[env]
ESP_LOG = "trace"

[target.xtensa-esp32-none-elf]
rustflags = [
    "-C",
    "link-arg=-Tlinkall.x",
    "-C",
    "link-arg=-nostartfiles",
    "-C",
    "link-arg=-Tesp32_rom_functions.x",
]
runner = "espflash flash --monitor"

[alias]
xtask = "run --package xtask --"
