target-dir := "`cargo metadata --format-version 1 | jq -r '.target_directory'`"

default:
    @ echo -n "\"Bindings\" module defines following "
    @ just --list

build:
    cargo build --locked --release --target ./xtensa-esp32-arduino-elf.json --package ember-bindings -Zbuild-std=compiler_builtins,core,alloc -Zbuild-std-features=,

update-arduino-lib: build
    echo {{target-dir}}
    cp {{target-dir}}/xtensa-esp32-arduino-elf/release/libember.a ../arduino/libraries/Ember/src/esp32/libEmberCore.a
    cp {{target-dir}}/bindings.hpp ../arduino/libraries/Ember/src/EmberCore.h
