[wokwi]
version = 1
firmware = "../../target/xtensa-esp32-none-elf/release/case-study-http-server"
elf = "../../target/xtensa-esp32-none-elf/release/case-study-http-server"

[[net.forward]]
from = "localhost:8080"
to = "target:80"