//! Global allocator using esp-idf-provided heap allocator functions.
//!
//! NOTE: This implementation is mostly generated by A.I.

use core::alloc::{GlobalAlloc, Layout};
use core::ptr;

#[allow(unused_doc_comments)]
/// cbindgen:ignore
unsafe extern "C" {
    fn malloc(size: usize) -> *mut u8;
    fn free(ptr: *mut u8);
    fn realloc(ptr: *mut u8, size: usize) -> *mut u8;
    fn heap_caps_aligned_alloc(alignment: usize, size: usize, caps: u32) -> *mut u8;
}

const MALLOC_CAP_8BIT: u32 = 1 << 2;
const MALLOC_CAP_DEFAULT: u32 = MALLOC_CAP_8BIT;

/// Custom allocator delegating to esp-idf-provided functions with proper alignment handling.
struct ESPIDFAllocator;

unsafe impl GlobalAlloc for ESPIDFAllocator {
    unsafe fn alloc(&self, layout: Layout) -> *mut u8 {
        let size = layout.size();
        let align = layout.align();

        if size == 0 {
            return ptr::null_mut();
        }

        // ESP-IDF's malloc provides 8-byte alignment by default
        // For larger alignment requirements, use memalign or heap_caps_aligned_alloc
        if align <= 8 {
            unsafe { malloc(size) }
        } else {
            // Use heap_caps_aligned_alloc for proper alignment
            unsafe { heap_caps_aligned_alloc(align, size, MALLOC_CAP_DEFAULT) }
        }
    }

    unsafe fn dealloc(&self, ptr: *mut u8, _layout: Layout) {
        if !ptr.is_null() {
            unsafe { free(ptr) };
        }
    }

    unsafe fn alloc_zeroed(&self, layout: Layout) -> *mut u8 {
        let size = layout.size();
        let ptr = unsafe { self.alloc(layout) };

        if !ptr.is_null() {
            // Zero out the allocated memory
            unsafe { ptr::write_bytes(ptr, 0, size) };
        }

        ptr
    }

    unsafe fn realloc(&self, ptr: *mut u8, layout: Layout, new_size: usize) -> *mut u8 {
        let old_size = layout.size();
        let align = layout.align();

        if new_size == 0 {
            unsafe { self.dealloc(ptr, layout) };
            return ptr::null_mut();
        }

        if ptr.is_null() {
            return unsafe { self.alloc(Layout::from_size_align_unchecked(new_size, align)) };
        }

        // If alignment is > 8, we need to handle realloc specially
        // because standard realloc doesn't preserve alignment guarantees
        if align <= 8 {
            // Standard realloc is safe for default alignment
            unsafe { realloc(ptr, new_size) }
        } else {
            // For aligned allocations, manually allocate and copy
            let new_layout = unsafe { Layout::from_size_align_unchecked(new_size, align) };
            let new_ptr = unsafe { self.alloc(new_layout) };

            if !new_ptr.is_null() {
                // Copy old data to new location
                let copy_size = if old_size < new_size {
                    old_size
                } else {
                    new_size
                };
                unsafe { ptr::copy_nonoverlapping(ptr, new_ptr, copy_size) };

                // Free old allocation
                unsafe { self.dealloc(ptr, layout) };
            }

            new_ptr
        }
    }
}

#[global_allocator]
static ALLOCATOR: ESPIDFAllocator = ESPIDFAllocator;
